# Generated by Django 3.2.8 on 2021-10-20 22:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailstreamforms.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelpage',
            name='content',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('sub_title', wagtail.core.blocks.TextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('button_text', wagtail.core.blocks.TextBlock(required=False)), ('button_link', wagtail.core.blocks.URLBlock(required=False)), ('video_text', wagtail.core.blocks.TextBlock(required=False)), ('video_link', wagtail.core.blocks.URLBlock(required=False))])), ('divider', wagtail.core.blocks.StructBlock([('description', wagtail.core.blocks.RichTextBlock(help_text='Any description you want for the divider', required=False)), ('logos', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=False), blank=True, help_text='Any logos you might want to display on the divider'))])), ('form', wagtail.core.blocks.StructBlock([('form', wagtailstreamforms.blocks.FormChooserBlock()), ('form_action', wagtail.core.blocks.CharBlock(help_text='The form post action. "" or "." for the current page or a url', required=False)), ('form_reference', wagtailstreamforms.blocks.InfoBlock(help_text='This form will be given a unique reference once saved', required=False))])), ('hotel_list', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.TextBlock()), ('description', wagtail.core.blocks.TextBlock(required=False))]))], blank=True, null=True),
        ),
    ]
